### ISSUE TITLE
Error when importing into clean project

### ISSUE THREAD

**Issue by zarat** [google-ar/arcore-unity-extensions#11]
I created an empty scene, switched to android platform, edited the player settings like app name, minimum api level = Android7(24) and imported

- ARFoundation 1.5.0-preview.7
- ARCore XR Plugin 2.1.2

thru the package manager. When done i get the following error messages

- Library\PackageCache\com.unity.xr.arcore@2.1.2\Runtime\ARCoreImageTrackingProvider.cs(35,60): error CS1715: 'ARCoreImageTrackingProvider.Provider.imageLibrary': type must be 'RuntimeReferenceImageLibrary' to match overridden member 'XRImageTrackingSubsystem.IProvider.imageLibrary'
- Library\PackageCache\com.unity.xr.arcore@2.1.2\Runtime\ARCoreImageTrackingProvider.cs(33,15): error CS0534: 'ARCoreImageTrackingProvider.Provider' does not implement inherited abstract member 'XRImageTrackingSubsystem.IProvider.imageLibrary.set'
- Library\PackageCache\com.unity.xr.arcore@2.1.2\Runtime\ARCoreImageTrackingProvider.cs(33,15): error CS0534: 'ARCoreImageTrackingProvider.Provider' does not implement inherited abstract member 'XRImageTrackingSubsystem.IProvider.CreateRuntimeLibrary(XRReferenceImageLibrary)'

Can i ignore it or is that a bug or something?

**Comment by zarat** [comment]
There seems to be some issues with ARCore 2.1.2 -> switching back to 2.0.2 does the job

**Comment by zarat** [comment]
Switching back to ARFoundation 2.0.2 does the job

**Comment by codemaker2015** [comment]
This is due to incompatible version of the packages. We know that each Unity 3D supporting only few list of versions and it is not backward compatible too. means if you are trying to open a project in Unity 3D 2018 version but it is actually developed on Unity 3D 2019 then definitely you will get some sort of package issues in your console.

The following are the packages with versions which is compatible in specific version of Unity.

**For Unity 2018:**

AR Foundation 1.0.0 — preview.22 (the latest for 1.0.0)
ARCore XR Plugin 1.0.0 — preview.24 (the latest for 1.0.0)
ARKit XR Plugin 1.0.0-preview.27 (the latest for 1.0.0)

**For Unity 2019:**

AR Foundation 2.0.2
ARCore XR Plugin 2.0.2
ARKit XR Plugin 2.0.2

You can add those packages from Package Manager. You can get it from Window --> Package Manager in Unity 2018.3 + versions. If you are trying to use this packages in Unity which version is less than 2018.3 then add those in your manifest.json file located under Packages folder.

```
{
  "dependencies": {
    ...
    "com.unity.xr.arcore": "1.0.0-preview.24",
    "com.unity.xr.arfoundation": "1.0.0-preview.22",
    "com.unity.xr.arkit": "1.0.0-preview.27"
  }
}
```
