### ISSUE TITLE
AddAnchor and ResolveAnchorOnTerrain are not available in ARFoundation 5.0.3

### ISSUE THREAD

**Issue by krkrkrrk** [google-ar/arcore-unity-extensions#112]
I am creating a project using ARFoundation 5.0.3 and the Geospatial API, but I cannot use AddAnchor or ResolveAnchorOnTerrain because of a NullReferenceException.

Does anyone know how to solve this problem?

**Comment by takeda1411123** [comment]
+1

**Comment by swardle** [comment]
I think if you are converting from ARF4 to ARF5 and maybe your scene file have a null in them probably becasue you have some wrong types like ARSessionOrigin vs XROrigin.  

I am guessing this as we had the same bug in our samples in our ARF5 scenes before the upcoming 1.45 release. 

If this is what you are doing check these references in your scene files if not please post adb logcat logs as I am not sure if this is your problem or not.

**Comment by mrichards** [comment]
This issue is believed to be fixed with the release of ARCore Extensions for AR Foundation version 1.45.0. This package separates the package into two versions, one compatible with AR Foundation 4 and AR Foundation 4. Please see [the Release Notes](https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0) for more detail.

Using the new version will probably resolve your problem as it addresses a few issues in our beta ARF5 support, but if it doesn’t, please reopen so I can take another look.

Thanks!
