### ISSUE TITLE
Migrate from Ar Session Origin To XrOrigin

### ISSUE THREAD

**Issue by hieuhsssws** [google-ar/arcore-unity-extensions#115]
Unity have just release AR Foundation 5.0, Which replace the Ar Session Origin to XR Origin. I can not find reference from AR Session Origin to XR Origin

**Comment by tichise** [comment]
I am having the same problem.

**Comment by hrkd** [comment]
https://github.com/holiday-studio/arcore-unity-extensions/commit/dbe4a1466c882108d2613f33308de6b6ae31b056

This fork might help you.

**Comment by timokorkalainen** [comment]
Note that the linked repo also removes Editor/Scripts/Internal/Analytics/Google.Protobuf.dll which needs to be included separately.

**Comment by singlerider** [comment]
I have opened a Pull Request (#125 ) that does not require the Google Protobuf to be modified. This allows for `XROrigin` to be used.

**Comment by jimmy-to-goldenowl** [comment]
I got a problem with the Editor/Scripts/Internal/Analytics/Google.Protobuf.dll too. 

Because my project is using the gRPC so we need the `Google.Protobuf.dll` in my project. The problem came when we install the `arcore-unity-extensions` package via GIT url `https://github.com/google-ar/arcore-unity-extensions.git`

Error: `Multiple precompiled assemblies with the same name Google.Protobuf.dll included on the current platform. Only one assembly with the same name is allowed per platform.`

Question: Do I need to remove the `Google.Protobuf.dll` from my project OR wait for the `arcore-unity-extensions` to remove it?

**Comment by singlerider** [comment]
> > Note that the linked repo also removes Editor/Scripts/Internal/Analytics/Google.Protobuf.dll which needs to be included separately.
> 
> I got a problem with the Editor/Scripts/Internal/Analytics/Google.Protobuf.dll too.
> 
> Because my project is using the gRPC so we need the Google.Protobuf.dll in my project. The problem came when we install the arcore-unity-extensions package via GIT url https://github.com/google-ar/arcore-unity-extensions.git
> 
> **Error**: Multiple precompiled assemblies with the same name Google.Protobuf.dll included on the current platform. Only one assembly with the same name is allowed per platform.
> 
> **Question**: Do I need to remove the Google.Protobuf.dll from my project OR wait for the arcore-unity-extensions to remove it?

Try my PR, instead: https://github.com/google-ar/arcore-unity-extensions/issues/115#issuecomment-1583289236

**Comment by jimmy-to-goldenowl** [comment]
> > > Note that the linked repo also removes Editor/Scripts/Internal/Analytics/Google.Protobuf.dll which needs to be included separately.
> > 
> > 
> > I got a problem with the Editor/Scripts/Internal/Analytics/Google.Protobuf.dll too.
> > Because my project is using the gRPC so we need the Google.Protobuf.dll in my project. The problem came when we install the arcore-unity-extensions package via GIT url https://github.com/google-ar/arcore-unity-extensions.git
> > **Error**: Multiple precompiled assemblies with the same name Google.Protobuf.dll included on the current platform. Only one assembly with the same name is allowed per platform.
> > **Question**: Do I need to remove the Google.Protobuf.dll from my project OR wait for the arcore-unity-extensions to remove it?
> 
> Try my PR, instead: [#115 (comment)](https://github.com/google-ar/arcore-unity-extensions/issues/115#issuecomment-1583289236)

Does your PR remove the `Google.Protobuf.dll`?

**Comment by singlerider** [comment]
> Does your PR remove the `Google.Protobuf.dll`?

No.

**Comment by mrichards** [comment]
This issue is believed to be fixed with the release of ARCore Extensions for AR Foundation version 1.45.0. This package separates the package into two versions, one compatible with AR Foundation 4 and AR Foundation 4. Please see [the Release Notes](https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0) for more detail.

Using the new version will probably resolve your problem as it addresses a few issues in our beta ARF5 support, but if it doesn’t, please reopen so I can take another look.

Thanks!****
