### ISSUE TITLE
How to make creator anchor runtime?

### ISSUE THREAD

**Issue by maowu** [google-ar/arcore-unity-extensions#174]
I wanna place GeoSpatial creator anchor in Editor runtime. 

But if I  try to create new anchor by this after application playing (on Editor, player play)

`ARGeospatialCreatorAnchor anchor = new GameObject("Newanchor").AddComponent<ARGeospatialCreatorAnchor>();
        anchor.Origin = _origin;
        anchor.AnchorManager = _anchorManager;
        anchor.Latitude = latitude;
        anchor.Longitude = longitude;
        anchor.AltitudeType = AnchorAltitudeType.WGS84;
        anchor.Altitude = talt;`

The anchor position is not correct (out of the range).
If there is any solution to place anchor by geo location in Editor?

**Comment by mrichards** [comment]
Hi @maowu, there is a known issue with the Editor-based API where the geospatial location and the Unity game world location are kept in sync during the call to the Anchor's `Update()` method. This can result in a situation where changes to the lat/lon/alt may be overwritten by previous changes to the (x,y,z) transform that occurred in the same frame. A similar thing may be happening in your case, where the newly-created anchor's original (x,y,z) transform are taking precedence over the updated lat/lon/alt.

This will be fixed in a future update, but for now you can work around it by updating the lat/lon/alt in the *next* frame after the object is created, not the same frame. Please let us know if that resolves the issue or not.

**Comment by posokhow** [comment]
I just noticed that the API to create an ARGeospatialCreatorAnchor is only available in Editor. 
I would like to use the ARCore Geospatial technology in a game where the anchors can be created over time by our team to enable more and more locations so the App would fetch these POIs regularly to update it's internal DB but that is not possible until the API is made read/write at runtime. Any plan on making this possible?

**Comment by 15kingben** [comment]
Can you achieve this by [adding Geospatial Anchors](https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/ARAnchorManagerExtensions#addanchor) using lat/lng/alt and orientation values, or the corresponding methods for terrain/rooftop anchors?

**Comment by posokhow** [comment]
Ben, thank you. Yes, that was the idea but the latitude/longitude setters on the ARGeoSpatialCreatorAnchor class are only available inside the Editor but I need to access these programmatically at runtime in order to create these anchors based on data that is pulled from the cloud at Runtime. This is a really unfortunate design choice as it limits a great deal of use cases. 
Now I am looking into instantiating prefabs that are pre-created on specific lat/long points but that is a limited work around. 
If you have a moment, I could drop by on campus to show you what we are doing with SparkMagic Karts. It's really cool tech. I dropped by Building 43 a few weeks ago and demoed it to Googlers and they were really excited by the tech.
(By the way, I used to work at [X] on Wing)

**Comment by 15kingben** [comment]
Note that [ARGeospatialAnchor](https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/ARGeospatialAnchor) and [ARGeospatialCreatorAnchor](https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/GeospatialCreator/ARGeospatialCreatorAnchor) are separate classes. The latter essentially wraps the former for setting lat/lng/alt values in the editor. ARGeospatialCreatorAnchor's allow you to preview anchors and fine-tune their locations within the Editor. However, if you are only interested in creating & manipulating anchors at Runtime, you should use the ARGeospatialAnchor APIs directly.

If you have a lat/lng/alt that you want to use to create an anchor at runtime, simply call https://developers.google.com/ar/reference/unity-arf/class/Google/XR/ARCoreExtensions/ARAnchorManagerExtensions#addanchor

**Comment by posokhow** [comment]
Ben, thank you so much for the clarification and my apologies for not reading the documentation more closely. You made my day yesterday as I was able to follow your advice and I am excited that it is possible to create ARCoreGeospatialAnchors programmatically as this supports our use case perfectly.

**Comment by NirajM** [comment]
@posokhow hey, I'm new to this tech and I'm also facing similar challenge that you seem to have faced. Would you be able to help me out by showing how exactly did you handle it? I know this is marked closed but if you could share an example. :)

**Comment by 15kingben** [comment]
The Geospatial Sample shows creating all types of Geospatial Anchors at runtime: https://github.com/google-ar/arcore-unity-extensions/blob/master/Samples~/Geospatial/Scripts/GeospatialController.cs
