### ISSUE TITLE
Quality and Occlusion on Streetscape Geometries

### ISSUE THREAD

**Issue by UluLord** [google-ar/arcore-unity-extensions#196]
I have 2 questions;

1. How can i increase geometry quality to BuildingLOD2? My Phone returning BuildingLOD1.
2. When I add AROcclusionManager to ARCamera, the shown geometry material is getting broken. How can i ise occlusion?

**Comment by 15kingben** [comment]
**1. How can i increase geometry quality to BuildingLOD2? My Phone returning BuildingLOD1.**

This LOD is not a function of the phone, but rather of what data Google has in that location. LOD2 is more common in urban environments, but also varies based on regional and local laws. To spot check, you can go to Google maps on a web browser and enable the terrain layer and pan down. Areas with streetscape geometry should also show 3D buildings in google maps.

**2. When I add AROcclusionManager to ARCamera, the shown geometry material is getting broken. How can i see occlusion?**

I'm not super familiar with [AROcclusionManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html), so you may need to manage the layers to ensure the occlusion looks correct. Can you share a video? Note that the LOD1 geometries may not work well for depth since they often have incorrect extents or building heights.

**Comment by UluLord** [comment]
So thanks for your answer 😊
