### ISSUE TITLE
ARCoreExtension GameObject for XR Origin in ARFoundation 5? 

### ISSUE THREAD

**Issue by yosun** [google-ar/arcore-unity-extensions#207]
Hi, are ARCore Extension gameObjects still required in AR Foundation 5? Should ARSessionOrigin be updated to XRSessionOrigin?

**Comment by devbridie** [comment]
Hey, there's some planned improvements on this in the near future. In the meantime you can use AR Foundation 5 and ignore warnings or use the [migration guide to fix up the session origins](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/version-history/migration-guide-5-x.html#xr-origin).

**Comment by mrichards** [comment]
This issue is believed to be fixed with the release of ARCore Extensions for AR Foundation version 1.45.0. This package separates the package into two versions, one compatible with AR Foundation 4 and AR Foundation 4. Please see [the Release Notes](https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0) for more detail.

Using the new version will probably resolve your problem as it addresses a few issues in our beta ARF5 support, but if it doesn’t, please reopen so I can take another look.

Thanks!
