### ISSUE TITLE
Sample project for ARFoundation 5 is outdated or not setup correctly

### ISSUE THREAD

**Issue by EwoudHerregat** [google-ar/arcore-unity-extensions#209]
After doing the entire setup for ARFoundation 5 (including adding the ARCORE_USE_ARF_5 Scripting symbol) the GeospatialArf5 scene is still not loading correctly. The XROrigin gameobject is not assigned in both the ARCoreExtensions and GeospatialController gameobject.

**Comment by devbridie** [comment]
Unforunately this is a known issue for the current release - we're looking to revamp this workflow in the next version of ARCore Extensions.

**Comment by mrichards** [comment]
This issue is believed to be fixed with the release of ARCore Extensions for AR Foundation version 1.45.0. This package separates the package into two versions, one compatible with AR Foundation 4 and AR Foundation 4. Please see [the Release Notes](https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0) for more detail.

Using the new version will probably resolve your problem as it addresses a few issues in our beta ARF5 support, but if it doesn’t, please reopen so I can take another look.

Thanks!
