### ISSUE TITLE
How do u use motion tracking to keep object follow the camera?

### ISSUE THREAD

**Issue by pinnakkkk** [google-ar/arcore-unity-extensions#55]
I cant understand how do i use it bcs in arcore sdk it was easy but with it being deprecated how can i do the same on this extension?

**Comment by chiangandy** [comment]
As I know, geospatial anchor is not allow to move position for anchor because it own and latitude and longitude in anchor, it need to destroy old one and create new one. for your requirement, a object follow camera, I think it is not a task doing in ARcore, it should use 3D model and attach belong to camera. I think it is not difficult in Unity development. 

I hope it can answer your quesiotn. :)

Andy

**Comment by mrichards** [comment]
Thank you for the helpful response @chiangandy!
