### ISSUE TITLE
Clarification on ARCore Cloud Anchor API quota

### ISSUE THREAD

**Issue by ian-phoria** [google-ar/arcore-unity-extensions#62]
I am utilising persistent cloud anchors in an Android & iOS application and every so often will receive a ErrorResourceExhausted response when attempting to resolve an anchor. 

This documentation page specifies a quota limit of 300 per minute: https://developers.google.com/ar/develop/unity-arf/cloud-anchors/developer-guide-android per _IP address and project._

We are resolving around 4 anchors (one after the other) every 15 seconds - and so should be nowhere near the quota of 300 per minute.

Can I please get clarification on exactly what is meant by IP address and project? 

IP address and project seems to imply that each unique IP address and unique project identifier has their own quota limit. So if two users have downloaded our application but are on two different networks, they should _not_ share the same quota? 

Is this correct?

**Comment by t5ujiri** [comment]
@devbridie So, does it matters only when the same machine calls the anchor query api more than 300 times per a minute? I've been hesitating to migrate from retiring Azure Spatial anchors due to the quotas.

**Comment by devbridie** [comment]
Hi,
One machine may operate using multiple IP addresses. Also, multiple machines may operate under the same IP address (from the outside world's perspective).

The important factor is the IP address GCP is seeing you from.

**Comment by t5ujiri** [comment]
@devbridie
My app is currently facing severe request throttling.
40 devices uses API concurrently. Some shares same global ip, others are not.
From my understanding, if devices uses different global ip by using VPN, those traffics will be treated as different quota scopes, which seem not be true.
Any idea what is the cause, and how to mitigate the throttling?

I'm asking this here because ARCore API team doesn't offer any official support.

<img width="2782" height="588" alt="Image" src="https://github.com/user-attachments/assets/db38bf3c-6c2f-45b7-a754-9b6b8a107015" />
