### ISSUE TITLE
Update to work with AR Foundation 5

### ISSUE THREAD

**Issue by pjarnfelt** [google-ar/arcore-unity-extensions#93]
It would be great to get a version that works with AR Foundation 5+. https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/index.html

It is mostly AR Origin that has changed to XR origin.

**Comment by tronantonio** [comment]
I'm Agree. I think is relativily simple make this change. It's terrible to back to old versions of Ar Foundation.

**Comment by mrichards** [comment]
This issue is believed to be fixed with the release of ARCore Extensions for AR Foundation version 1.45.0. This package separates the package into two versions, one compatible with AR Foundation 4 and AR Foundation 4. Please see [the Release Notes](https://github.com/google-ar/arcore-unity-extensions/releases/tag/1.45.0) for more detail.

Using the new version will probably resolve your problem as it addresses a few issues in our beta ARF5 support, but if it doesn’t, please reopen so I can take another look.

Thanks!
